video_stream_params:
  # Stream Params
  algorithm: motion
  name: home-cam
  resize_multiplier: 1
  storage_location: "/home/carmelog/Desktop/storage/"
  # storage_location: "/var/lib/motioneye/Camera1/"

  # Save/Display Params
  visualize: True
  save_video: True
  save_logs: False
  show_algo: True
  # Playback Params
  playback: False
  playback_rate: 0.0001
  # Other Params
  verbose: False
  extra_sleep: 0.0
  saved_video_length: 20

algo_params:
  blur: 9
  move_thresh: 25
  min_area: 250
  cooldown_frames: 25
