video_stream_params:
  # Stream Params
  algorithm: Motion
  name: HomeCamera
  resize_multiplier: 1
  storage_location: "/home/carmelo/Desktop/storage/"
  ip: "rtsp://192.168.1.15:8554/mjpeg/1"
  # Save/Display Params
  visualize: False
  save_video: False
  save_logs: False
  show_algo: True
  # Playback Params
  playback: False
  playback_rate: 0.0001
  # Other Params
  verbose: False
  extra_sleep: 0.5
  saved_video_length: 600

algo_params:
  blur: 7
  move_thresh: 18
  min_area: 150
  cooldown_frames: 25
