video_stream_params:
  # Stream Params
  algorithm: motion
  name: home-cam
  resize_multiplier: 1
  storage_location: "/home/carmelog/Desktop/storage/"
  # storage_location: "/var/lib/motioneye/Camera1/"
  ip: "rtsp://admin:lunajake101@192.168.1.17:554/cam/realmonitor?channel=1&subtype=0"
  # ip: /home/carmelog/Desktop/storage/sync/HomeCamera_Motion_2023-02-23T010000_.avi
  # Save/Display Params
  visualize: False
  save_video: True
  save_logs: False
  show_algo: True
  # Playback Params
  playback: False
  playback_rate: 0.0001
  # Other Params
  verbose: False
  extra_sleep: 0.00001
  saved_video_length: 60

algo_params:
  blur: 9
  move_thresh: 25
  min_area: 250
  cooldown_frames: 25
